name: Data Engineering CI
on:
    push:
        branches:
            - main
            - feat/*
            - fix/*

jobs:
    run-ci:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                python-version: 3.10

            - name: Setup pipenv and switch
              run: |
                pip install pipenv
                pipenv install
                pipenv shell

            - name: Install dependencies
              run: make install

            - name: Lint
              run: make lint

            - name: Type check
              run: make type-check

            # - name: Test
            #   run: make test

            # - name: Publish coverage report
            #   uses: codecov/codecov-action@v2.1.0
            #   with:
            #     token: ${{ secrets.CODECOV_TOKEN }}
            #     file: ./coverage.xml
            #     flags: unittests
            #     name: codecov-umbrella
            #     fail_ci_if_error: true
